// Copyright Contributors to the Open Cluster Management project

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: search_indexer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	OverwriteState  bool                   `protobuf:"varint,2,opt,name=overwrite_state,json=overwriteState,proto3" json:"overwrite_state,omitempty"`
	AddResources    []*Resource            `protobuf:"bytes,3,rep,name=add_resources,json=addResources,proto3" json:"add_resources,omitempty"`
	UpdateResources []*Resource            `protobuf:"bytes,4,rep,name=update_resources,json=updateResources,proto3" json:"update_resources,omitempty"`
	DeleteResources []*DeleteResourceEvent `protobuf:"bytes,5,rep,name=delete_resources,json=deleteResources,proto3" json:"delete_resources,omitempty"`
	AddEdges        []*Edge                `protobuf:"bytes,6,rep,name=add_edges,json=addEdges,proto3" json:"add_edges,omitempty"`
	DeleteEdges     []*Edge                `protobuf:"bytes,7,rep,name=delete_edges,json=deleteEdges,proto3" json:"delete_edges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_search_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *SyncRequest) GetOverwriteState() bool {
	if x != nil {
		return x.OverwriteState
	}
	return false
}

func (x *SyncRequest) GetAddResources() []*Resource {
	if x != nil {
		return x.AddResources
	}
	return nil
}

func (x *SyncRequest) GetUpdateResources() []*Resource {
	if x != nil {
		return x.UpdateResources
	}
	return nil
}

func (x *SyncRequest) GetDeleteResources() []*DeleteResourceEvent {
	if x != nil {
		return x.DeleteResources
	}
	return nil
}

func (x *SyncRequest) GetAddEdges() []*Edge {
	if x != nil {
		return x.AddEdges
	}
	return nil
}

func (x *SyncRequest) GetDeleteEdges() []*Edge {
	if x != nil {
		return x.DeleteEdges
	}
	return nil
}

type SyncChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session management
	SessionId      string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClusterId      string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	IsFirstChunk   bool   `protobuf:"varint,3,opt,name=is_first_chunk,json=isFirstChunk,proto3" json:"is_first_chunk,omitempty"`
	IsLastChunk    bool   `protobuf:"varint,4,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	OverwriteState bool   `protobuf:"varint,5,opt,name=overwrite_state,json=overwriteState,proto3" json:"overwrite_state,omitempty"`
	// Data in this chunk
	AddResources    []*Resource            `protobuf:"bytes,6,rep,name=add_resources,json=addResources,proto3" json:"add_resources,omitempty"`
	UpdateResources []*Resource            `protobuf:"bytes,7,rep,name=update_resources,json=updateResources,proto3" json:"update_resources,omitempty"`
	DeleteResources []*DeleteResourceEvent `protobuf:"bytes,8,rep,name=delete_resources,json=deleteResources,proto3" json:"delete_resources,omitempty"`
	AddEdges        []*Edge                `protobuf:"bytes,9,rep,name=add_edges,json=addEdges,proto3" json:"add_edges,omitempty"`
	DeleteEdges     []*Edge                `protobuf:"bytes,10,rep,name=delete_edges,json=deleteEdges,proto3" json:"delete_edges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncChunk) Reset() {
	*x = SyncChunk{}
	mi := &file_search_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChunk) ProtoMessage() {}

func (x *SyncChunk) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChunk.ProtoReflect.Descriptor instead.
func (*SyncChunk) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *SyncChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyncChunk) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *SyncChunk) GetIsFirstChunk() bool {
	if x != nil {
		return x.IsFirstChunk
	}
	return false
}

func (x *SyncChunk) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *SyncChunk) GetOverwriteState() bool {
	if x != nil {
		return x.OverwriteState
	}
	return false
}

func (x *SyncChunk) GetAddResources() []*Resource {
	if x != nil {
		return x.AddResources
	}
	return nil
}

func (x *SyncChunk) GetUpdateResources() []*Resource {
	if x != nil {
		return x.UpdateResources
	}
	return nil
}

func (x *SyncChunk) GetDeleteResources() []*DeleteResourceEvent {
	if x != nil {
		return x.DeleteResources
	}
	return nil
}

func (x *SyncChunk) GetAddEdges() []*Edge {
	if x != nil {
		return x.AddEdges
	}
	return nil
}

func (x *SyncChunk) GetDeleteEdges() []*Edge {
	if x != nil {
		return x.DeleteEdges
	}
	return nil
}

type SyncResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalAdded        int32                  `protobuf:"varint,1,opt,name=total_added,json=totalAdded,proto3" json:"total_added,omitempty"`
	TotalUpdated      int32                  `protobuf:"varint,2,opt,name=total_updated,json=totalUpdated,proto3" json:"total_updated,omitempty"`
	TotalDeleted      int32                  `protobuf:"varint,3,opt,name=total_deleted,json=totalDeleted,proto3" json:"total_deleted,omitempty"`
	TotalResources    int32                  `protobuf:"varint,4,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	TotalEdgesAdded   int32                  `protobuf:"varint,5,opt,name=total_edges_added,json=totalEdgesAdded,proto3" json:"total_edges_added,omitempty"`
	TotalEdgesDeleted int32                  `protobuf:"varint,6,opt,name=total_edges_deleted,json=totalEdgesDeleted,proto3" json:"total_edges_deleted,omitempty"`
	TotalEdges        int32                  `protobuf:"varint,7,opt,name=total_edges,json=totalEdges,proto3" json:"total_edges,omitempty"`
	AddErrors         []*SyncError           `protobuf:"bytes,8,rep,name=add_errors,json=addErrors,proto3" json:"add_errors,omitempty"`
	UpdateErrors      []*SyncError           `protobuf:"bytes,9,rep,name=update_errors,json=updateErrors,proto3" json:"update_errors,omitempty"`
	DeleteErrors      []*SyncError           `protobuf:"bytes,10,rep,name=delete_errors,json=deleteErrors,proto3" json:"delete_errors,omitempty"`
	AddEdgeErrors     []*SyncError           `protobuf:"bytes,11,rep,name=add_edge_errors,json=addEdgeErrors,proto3" json:"add_edge_errors,omitempty"`
	DeleteEdgeErrors  []*SyncError           `protobuf:"bytes,12,rep,name=delete_edge_errors,json=deleteEdgeErrors,proto3" json:"delete_edge_errors,omitempty"`
	Version           string                 `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_search_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *SyncResponse) GetTotalAdded() int32 {
	if x != nil {
		return x.TotalAdded
	}
	return 0
}

func (x *SyncResponse) GetTotalUpdated() int32 {
	if x != nil {
		return x.TotalUpdated
	}
	return 0
}

func (x *SyncResponse) GetTotalDeleted() int32 {
	if x != nil {
		return x.TotalDeleted
	}
	return 0
}

func (x *SyncResponse) GetTotalResources() int32 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *SyncResponse) GetTotalEdgesAdded() int32 {
	if x != nil {
		return x.TotalEdgesAdded
	}
	return 0
}

func (x *SyncResponse) GetTotalEdgesDeleted() int32 {
	if x != nil {
		return x.TotalEdgesDeleted
	}
	return 0
}

func (x *SyncResponse) GetTotalEdges() int32 {
	if x != nil {
		return x.TotalEdges
	}
	return 0
}

func (x *SyncResponse) GetAddErrors() []*SyncError {
	if x != nil {
		return x.AddErrors
	}
	return nil
}

func (x *SyncResponse) GetUpdateErrors() []*SyncError {
	if x != nil {
		return x.UpdateErrors
	}
	return nil
}

func (x *SyncResponse) GetDeleteErrors() []*SyncError {
	if x != nil {
		return x.DeleteErrors
	}
	return nil
}

func (x *SyncResponse) GetAddEdgeErrors() []*SyncError {
	if x != nil {
		return x.AddEdgeErrors
	}
	return nil
}

func (x *SyncResponse) GetDeleteEdgeErrors() []*SyncError {
	if x != nil {
		return x.DeleteEdgeErrors
	}
	return nil
}

func (x *SyncResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Resource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Uid            string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceString string                 `protobuf:"bytes,3,opt,name=resource_string,json=resourceString,proto3" json:"resource_string,omitempty"`
	Properties     map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_search_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Resource) GetResourceString() string {
	if x != nil {
		return x.ResourceString
	}
	return ""
}

func (x *Resource) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUid     string                 `protobuf:"bytes,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	DestUid       string                 `protobuf:"bytes,2,opt,name=dest_uid,json=destUid,proto3" json:"dest_uid,omitempty"`
	EdgeType      string                 `protobuf:"bytes,3,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	SourceKind    string                 `protobuf:"bytes,4,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	DestKind      string                 `protobuf:"bytes,5,opt,name=dest_kind,json=destKind,proto3" json:"dest_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_search_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *Edge) GetSourceUid() string {
	if x != nil {
		return x.SourceUid
	}
	return ""
}

func (x *Edge) GetDestUid() string {
	if x != nil {
		return x.DestUid
	}
	return ""
}

func (x *Edge) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *Edge) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *Edge) GetDestKind() string {
	if x != nil {
		return x.DestKind
	}
	return ""
}

type DeleteResourceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceEvent) Reset() {
	*x = DeleteResourceEvent{}
	mi := &file_search_indexer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceEvent) ProtoMessage() {}

func (x *DeleteResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceEvent.ProtoReflect.Descriptor instead.
func (*DeleteResourceEvent) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResourceEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type SyncError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceUid   string                 `protobuf:"bytes,1,opt,name=resource_uid,json=resourceUid,proto3" json:"resource_uid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncError) Reset() {
	*x = SyncError{}
	mi := &file_search_indexer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncError) ProtoMessage() {}

func (x *SyncError) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncError.ProtoReflect.Descriptor instead.
func (*SyncError) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{6}
}

func (x *SyncError) GetResourceUid() string {
	if x != nil {
		return x.ResourceUid
	}
	return ""
}

func (x *SyncError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_search_indexer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_search_indexer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_indexer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_search_indexer_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_search_indexer_proto protoreflect.FileDescriptor

const file_search_indexer_proto_rawDesc = "" +
	"\n" +
	"\x14search_indexer.proto\x12\x0esearch.indexer\"\x95\x03\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12'\n" +
	"\x0foverwrite_state\x18\x02 \x01(\bR\x0eoverwriteState\x12=\n" +
	"\radd_resources\x18\x03 \x03(\v2\x18.search.indexer.ResourceR\faddResources\x12C\n" +
	"\x10update_resources\x18\x04 \x03(\v2\x18.search.indexer.ResourceR\x0fupdateResources\x12N\n" +
	"\x10delete_resources\x18\x05 \x03(\v2#.search.indexer.DeleteResourceEventR\x0fdeleteResources\x121\n" +
	"\tadd_edges\x18\x06 \x03(\v2\x14.search.indexer.EdgeR\baddEdges\x127\n" +
	"\fdelete_edges\x18\a \x03(\v2\x14.search.indexer.EdgeR\vdeleteEdges\"\xfc\x03\n" +
	"\tSyncChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12$\n" +
	"\x0eis_first_chunk\x18\x03 \x01(\bR\fisFirstChunk\x12\"\n" +
	"\ris_last_chunk\x18\x04 \x01(\bR\visLastChunk\x12'\n" +
	"\x0foverwrite_state\x18\x05 \x01(\bR\x0eoverwriteState\x12=\n" +
	"\radd_resources\x18\x06 \x03(\v2\x18.search.indexer.ResourceR\faddResources\x12C\n" +
	"\x10update_resources\x18\a \x03(\v2\x18.search.indexer.ResourceR\x0fupdateResources\x12N\n" +
	"\x10delete_resources\x18\b \x03(\v2#.search.indexer.DeleteResourceEventR\x0fdeleteResources\x121\n" +
	"\tadd_edges\x18\t \x03(\v2\x14.search.indexer.EdgeR\baddEdges\x127\n" +
	"\fdelete_edges\x18\n" +
	" \x03(\v2\x14.search.indexer.EdgeR\vdeleteEdges\"\xff\x04\n" +
	"\fSyncResponse\x12\x1f\n" +
	"\vtotal_added\x18\x01 \x01(\x05R\n" +
	"totalAdded\x12#\n" +
	"\rtotal_updated\x18\x02 \x01(\x05R\ftotalUpdated\x12#\n" +
	"\rtotal_deleted\x18\x03 \x01(\x05R\ftotalDeleted\x12'\n" +
	"\x0ftotal_resources\x18\x04 \x01(\x05R\x0etotalResources\x12*\n" +
	"\x11total_edges_added\x18\x05 \x01(\x05R\x0ftotalEdgesAdded\x12.\n" +
	"\x13total_edges_deleted\x18\x06 \x01(\x05R\x11totalEdgesDeleted\x12\x1f\n" +
	"\vtotal_edges\x18\a \x01(\x05R\n" +
	"totalEdges\x128\n" +
	"\n" +
	"add_errors\x18\b \x03(\v2\x19.search.indexer.SyncErrorR\taddErrors\x12>\n" +
	"\rupdate_errors\x18\t \x03(\v2\x19.search.indexer.SyncErrorR\fupdateErrors\x12>\n" +
	"\rdelete_errors\x18\n" +
	" \x03(\v2\x19.search.indexer.SyncErrorR\fdeleteErrors\x12A\n" +
	"\x0fadd_edge_errors\x18\v \x03(\v2\x19.search.indexer.SyncErrorR\raddEdgeErrors\x12G\n" +
	"\x12delete_edge_errors\x18\f \x03(\v2\x19.search.indexer.SyncErrorR\x10deleteEdgeErrors\x12\x18\n" +
	"\aversion\x18\r \x01(\tR\aversion\"\xe2\x01\n" +
	"\bResource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12'\n" +
	"\x0fresource_string\x18\x03 \x01(\tR\x0eresourceString\x12H\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2(.search.indexer.Resource.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x04Edge\x12\x1d\n" +
	"\n" +
	"source_uid\x18\x01 \x01(\tR\tsourceUid\x12\x19\n" +
	"\bdest_uid\x18\x02 \x01(\tR\adestUid\x12\x1b\n" +
	"\tedge_type\x18\x03 \x01(\tR\bedgeType\x12\x1f\n" +
	"\vsource_kind\x18\x04 \x01(\tR\n" +
	"sourceKind\x12\x1b\n" +
	"\tdest_kind\x18\x05 \x01(\tR\bdestKind\"'\n" +
	"\x13DeleteResourceEvent\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"H\n" +
	"\tSyncError\x12!\n" +
	"\fresource_uid\x18\x01 \x01(\tR\vresourceUid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe4\x01\n" +
	"\rSearchIndexer\x12A\n" +
	"\x04Sync\x12\x1b.search.indexer.SyncRequest\x1a\x1c.search.indexer.SyncResponse\x12G\n" +
	"\n" +
	"StreamSync\x12\x19.search.indexer.SyncChunk\x1a\x1c.search.indexer.SyncResponse(\x01\x12G\n" +
	"\x06Health\x12\x1d.search.indexer.HealthRequest\x1a\x1e.search.indexer.HealthResponseB5Z3github.com/stolostron/search-indexer/pkg/grpc/protob\x06proto3"

var (
	file_search_indexer_proto_rawDescOnce sync.Once
	file_search_indexer_proto_rawDescData []byte
)

func file_search_indexer_proto_rawDescGZIP() []byte {
	file_search_indexer_proto_rawDescOnce.Do(func() {
		file_search_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_indexer_proto_rawDesc), len(file_search_indexer_proto_rawDesc)))
	})
	return file_search_indexer_proto_rawDescData
}

var file_search_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_search_indexer_proto_goTypes = []any{
	(*SyncRequest)(nil),         // 0: search.indexer.SyncRequest
	(*SyncChunk)(nil),           // 1: search.indexer.SyncChunk
	(*SyncResponse)(nil),        // 2: search.indexer.SyncResponse
	(*Resource)(nil),            // 3: search.indexer.Resource
	(*Edge)(nil),                // 4: search.indexer.Edge
	(*DeleteResourceEvent)(nil), // 5: search.indexer.DeleteResourceEvent
	(*SyncError)(nil),           // 6: search.indexer.SyncError
	(*HealthRequest)(nil),       // 7: search.indexer.HealthRequest
	(*HealthResponse)(nil),      // 8: search.indexer.HealthResponse
	nil,                         // 9: search.indexer.Resource.PropertiesEntry
}
var file_search_indexer_proto_depIdxs = []int32{
	3,  // 0: search.indexer.SyncRequest.add_resources:type_name -> search.indexer.Resource
	3,  // 1: search.indexer.SyncRequest.update_resources:type_name -> search.indexer.Resource
	5,  // 2: search.indexer.SyncRequest.delete_resources:type_name -> search.indexer.DeleteResourceEvent
	4,  // 3: search.indexer.SyncRequest.add_edges:type_name -> search.indexer.Edge
	4,  // 4: search.indexer.SyncRequest.delete_edges:type_name -> search.indexer.Edge
	3,  // 5: search.indexer.SyncChunk.add_resources:type_name -> search.indexer.Resource
	3,  // 6: search.indexer.SyncChunk.update_resources:type_name -> search.indexer.Resource
	5,  // 7: search.indexer.SyncChunk.delete_resources:type_name -> search.indexer.DeleteResourceEvent
	4,  // 8: search.indexer.SyncChunk.add_edges:type_name -> search.indexer.Edge
	4,  // 9: search.indexer.SyncChunk.delete_edges:type_name -> search.indexer.Edge
	6,  // 10: search.indexer.SyncResponse.add_errors:type_name -> search.indexer.SyncError
	6,  // 11: search.indexer.SyncResponse.update_errors:type_name -> search.indexer.SyncError
	6,  // 12: search.indexer.SyncResponse.delete_errors:type_name -> search.indexer.SyncError
	6,  // 13: search.indexer.SyncResponse.add_edge_errors:type_name -> search.indexer.SyncError
	6,  // 14: search.indexer.SyncResponse.delete_edge_errors:type_name -> search.indexer.SyncError
	9,  // 15: search.indexer.Resource.properties:type_name -> search.indexer.Resource.PropertiesEntry
	0,  // 16: search.indexer.SearchIndexer.Sync:input_type -> search.indexer.SyncRequest
	1,  // 17: search.indexer.SearchIndexer.StreamSync:input_type -> search.indexer.SyncChunk
	7,  // 18: search.indexer.SearchIndexer.Health:input_type -> search.indexer.HealthRequest
	2,  // 19: search.indexer.SearchIndexer.Sync:output_type -> search.indexer.SyncResponse
	2,  // 20: search.indexer.SearchIndexer.StreamSync:output_type -> search.indexer.SyncResponse
	8,  // 21: search.indexer.SearchIndexer.Health:output_type -> search.indexer.HealthResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_search_indexer_proto_init() }
func file_search_indexer_proto_init() {
	if File_search_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_indexer_proto_rawDesc), len(file_search_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_indexer_proto_goTypes,
		DependencyIndexes: file_search_indexer_proto_depIdxs,
		MessageInfos:      file_search_indexer_proto_msgTypes,
	}.Build()
	File_search_indexer_proto = out.File
	file_search_indexer_proto_goTypes = nil
	file_search_indexer_proto_depIdxs = nil
}
